import type { Metadata } from "next";
import Header from "./components/sections/header";
import Footer from "./components/sections/footer";
import "./css/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full scroll-smooth antialiased">
      <body className="bg-gris antialiased">
        <Header />
        <div className="main">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
